// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: link.
// - Entity ID: 102019b6141e88672548fc9655f0d56014d.
// - Entity Version: 102019dc5e602df711080d3413bb0c1c2ea.
// - Task ID: 69e473bd4375fa99fd8e28b9.
// - Task Root ID: 6950313a5b551409b7ff44aa.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for LinkModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface LinkModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  url: string;
  display_name: string;
}

/**
 * ORM class for Link entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class LinkORM {
  private static instance: LinkORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b6141e88672548fc9655f0d56014d';
    this.entityName = 'link';
    this.entityVersion = '102019dc5e602df711080d3413bb0c1c2ea';
    this.taskId = '69e473bd4375fa99fd8e28b9';
    this.taskRootId = '6950313a5b551409b7ff44aa';
  }

  /**
   * Get singleton instance of LinkORM
   */
  public static getInstance(): LinkORM {
    if (!LinkORM.instance) {
      LinkORM.instance = new LinkORM();
    }
    
    return LinkORM.instance;
  }

  /**
   * Get link by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getLinkByIDs(ids: string[]): Promise<LinkModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete link by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteLinkByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Link records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllLink(): Promise<LinkModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Link record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertLink(data: LinkModel[]): Promise<LinkModel[]> {
    const structured = data.map((item) => CreateData(LinkModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Link records
   */
  async purgeAllLink(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Link records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listLink(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[LinkModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get link by Id index
   * This function gets data by index.
   */
  async getLinkById(
    id: string,
  ): Promise<LinkModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) link by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLinkById(
    id: string,
    data: LinkModel
  ): Promise<LinkModel[]> {
    const index = createIndexId(
      id
    );

    const values = LinkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete link by Id index
   */
  async deleteLinkById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get link by DataCreator index
   * This function gets data by index.
   */
  async getLinkByDataCreator(
    data_creator: string,
  ): Promise<LinkModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) link by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLinkByDataCreator(
    data_creator: string,
    data: LinkModel
  ): Promise<LinkModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = LinkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete link by DataCreator index
   */
  async deleteLinkByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get link by DataUpdater index
   * This function gets data by index.
   */
  async getLinkByDataUpdater(
    data_updater: string,
  ): Promise<LinkModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) link by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLinkByDataUpdater(
    data_updater: string,
    data: LinkModel
  ): Promise<LinkModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = LinkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete link by DataUpdater index
   */
  async deleteLinkByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get link by CreateTimeDataCreator index
   * This function gets data by index.
   */
  async getLinkByCreateTimeDataCreator(
    create_time: string,
    data_creator: string,
  ): Promise<LinkModel[]> {
    const index = createIndexCreateTimeDataCreator(
      create_time,
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) link by CreateTimeDataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLinkByCreateTimeDataCreator(
    create_time: string,
    data_creator: string,
    data: LinkModel
  ): Promise<LinkModel[]> {
    const index = createIndexCreateTimeDataCreator(
      create_time,
      data_creator
    );

    const values = LinkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete link by CreateTimeDataCreator index
   */
  async deleteLinkByCreateTimeDataCreator(
    create_time: string,
    data_creator: string
  ): Promise<void> {
    const index = createIndexCreateTimeDataCreator(
      create_time,
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get link by DataCreatorDisplayName index
   * This function gets data by index.
   */
  async getLinkByDataCreatorDisplayName(
    data_creator: string,
    display_name: string,
  ): Promise<LinkModel[]> {
    const index = createIndexDataCreatorDisplayName(
      data_creator,
      display_name
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) link by DataCreatorDisplayName index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLinkByDataCreatorDisplayName(
    data_creator: string,
    display_name: string,
    data: LinkModel
  ): Promise<LinkModel[]> {
    const index = createIndexDataCreatorDisplayName(
      data_creator,
      display_name
    );

    const values = LinkModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete link by DataCreatorDisplayName index
   */
  async deleteLinkByDataCreatorDisplayName(
    data_creator: string,
    display_name: string
  ): Promise<void> {
    const index = createIndexDataCreatorDisplayName(
      data_creator,
      display_name
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to LinkModel data array
   */
  private resultToData(values: Data[]): LinkModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return LinkModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as LinkModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized LinkModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is LinkModel => item !== null);
  }
}

/**
 * Convert LinkModel data to Value array
 */
function LinkModelToValues(data: LinkModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'url', type: DataType.string, defaultValue: '' },
    { key: 'display_name', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof LinkModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to LinkModel data
 */
function LinkModelFromValues(values: Value[]): LinkModel {
  const data: Partial<LinkModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'url':
        data.url = ParseValue(value, DataType.string) as string;
        break;
      case 'display_name':
        data.display_name = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as LinkModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for CreateTimeDataCreator fields
 */
function createIndexCreateTimeDataCreator(
  create_time: string,
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['create_time', 'data_creator'],
    values
  };
}
/**
 * Create index for DataCreatorDisplayName fields
 */
function createIndexDataCreatorDisplayName(
  data_creator: string,
  display_name: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
    CreateValue(DataType.string, display_name, 'display_name'),
  ];

  return {
    fields: ['data_creator', 'display_name'],
    values
  };
}

export default LinkORM;